### ISSUE TITLE
Can't make it

### ISSUE THREAD

**Issue by qiuyi21** [tihmstar/libgeneral#1]
I am using macOS 10.14.6

> Configuration for img4tool-158:
-------------------------------------------

  install prefix ..........: /usr/local
  have plist ..............: yes
  crypto backend ..........: openssl
  compiler ................: gcc

  Now type 'make' to build img4tool-158,
  and then 'make install' for installation.

QiuyiMBP:img4tool qiuyi$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in img4tool
Makefile:534: ../external/libgeneral/libgeneral/.deps/libimg4tool_la-exception.Plo: No such file or directory
make[2]: *** No rule to make target `../external/libgeneral/libgeneral/.deps/libimg4tool_la-exception.Plo'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by tihmstar** [comment]
Got you buddy https://github.com/tihmstar/libgeneral/releases
