### ISSUE TITLE
vasprintf undeclared when attempting to compile with mingw64 on Windows

### ISSUE THREAD

**Issue by DanTheMann15** [tihmstar/libgeneral#2]
This occurs on both MSYS2 and Cygwin when attempting to compile on Windows x86_64

`exception.cpp: In constructor ‘tihmstar::exception::exception(int, const char*, const char*, ...)’:
exception.cpp:23:9: error: ‘vasprintf’ was not declared in this scope
         vasprintf(&_err, err, ap);
         ^~~~~~~~~
exception.cpp:23:9: note: suggested alternative: ‘vsprintf’
         vasprintf(&_err, err, ap);
         ^~~~~~~~~
         vsprintf
make[2]: *** [Makefile:451: libgeneral_la-exception.lo] Error 1
make[2]: Leaving directory '/cygdrive/c/Users/Daniel/Desktop/libgeneral/libgeneral'
make[1]: *** [Makefile:463: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/Daniel/Desktop/libgeneral'
make: *** [Makefile:372: all] Error 2
`

**Comment by haen7** [comment]
Try adding `#define _GNU_SOURCE` to `exception.cpp`.

**Comment by DanTheMann15** [comment]
this quick little patch made it work, how about that.

**Comment by Merculous** [comment]
> Try adding `#define _GNU_SOURCE` to `exception.cpp`.

This fixed it for sure. Thanks!
